[package]
name = "restaurant_api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dashmap = "6.0.1"
rand = { version = "0.8.5", features = [] }
serde = { version = "1.0.204", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v4"] }
